.cpu Z80
.org 0x0000
.engine liveprogramming/liveprogramming

;CONFIGS
LENGTH EQU  32

print_buffer:   PUSH HL              ;Preserve HL,BC,AF
                PUSH BC
                PUSH AF
                LD HL,LINE_BUFFER_16 ;Load Buffer Pointer
                LD B,LENGTH          ;Load Buffer Size
                LD A,0x0D            ;Move back to the beginning of the line
                OUT (1),A            ;Output the CR character
print_loop:     LD A,(HL)            ;Load Character from Buffer
                OUT (1),A            ;Output Character
                INC HL               ;Increase Buffer Pointer
                DEC B                ;Decrease Counter
                JR NZ,print_loop     ;Check Counter and continue loop if nonZero
                POP AF               ;Restore AF BC HL
                POP BC
                POP HL
                RET
init:           LD SP,$FFFF          ;Init Stack
                LD HL,LINE_BUFFER_16 ;Init Pointer
                LD DE,LINE_BUFFER_16 + LENGTH - 1     ;Limit the Character Per Line
                JP main
main:           CALL PRINT_BUFFER  ;Update Console

                IN A,(0)           ;Check if Incoming Character
                AND 1              ;Check the LSB
                JR Z,main          ;Skip Loop If Nothing is comming from Console :|

                IN A,(1)           ;Input Character
                PUSH HL            ;Preserve HL
                DEC HL             ;DEC for Checking
                bit 7,H            ;Check If Less Than 0x8000 After Decrease by 1
                POP HL             ;Restore HL (Does not affect flags)
                JR Z,ContinueSpecM1;Ignore BackSpace if it will cause UnderFlow
                CP 0x08            ;Check if its BackSpace
                JR NZ,ContinueSpecM1 ;If Not,Skip
                LD (HL)," "        ;Clear Current Buffer Pointer Address Data
                DEC HL             ;Decrease the Buffer Pointer Address
                LD (HL),"|"        ;Replace with the "|" symbol
                JR main            ;Continue the Loop as BackSpace is already handled
ContinueSpecM1: EX DE,HL           ;Exchange HL and DE for Difference Calculation
                PUSH HL            ;Preserve HL
                AND A              ;Clear Flag
                SBC HL,DE          ;to HL-DE (but it was exchanged so its actually DE-HL)
                POP HL             ;restore HL(But Actually Storing DE's content ) , not affecting Flags
                EX DE,HL           ;Exchange HL back
                JR Z,main          ;If Reached Limit,Ignore Input
                LD (HL),A          ;Load Character into Buffer
                INC HL             ;Inc Buffer Pointer
                LD (HL),0x7C       ;Load Character '|' on to the next place
                JP main            ;LOOP
.ent init             ;Boot in INIT (For Better Compatibility,put init onto 0x0000 for CP/M etc. execution)
.org 0x8000           ;RAM Part
Line_Buffer_16:    DB "|"," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "  ;Default Line_Buffer


;I think I done enough today :)
;Next time i will do the Enter and also some erm address editing Command

;All Command i want:
;W HEX4DIGITADDRESS HEX2DIGITDATA     for writing into ram
;R HEX4DIGITADDRESS                   for reading the RAM onto screen
;EXEC ADDRESS                         CALL that ADDRESS
;(The above thing should(I think...?) be able to let me write some cool programs with Machine Code (Yeah u heard it right,MACHINE CODE :skull: not assembly anymore))