.cpu Z80
.org 0x0000
.engine liveprogramming/liveprogramming

;CONFIGS
LENGTH EQU  32
reset_buffer:   PUSH DE                       ;Preserve DE BC
                PUSH BC  
                LD (HL)," "                   ;Remove Current Cursor
                CALL PRINT_BUFFER             ;Update to remove the Cursor First
                LD HL, LINE_BUFFER_16_DEFAULT ;Load the Resource Address
                LD DE, LINE_BUFFER_16         ;Load the Destination Address
                LD BC, 32                     ;Data Length
                LDIR                          ;Load with Increase Pointer
                POP BC                        ;Restore BC
                POP DE                        ;Restore DE
                LD HL,Line_Buffer_16          ;Restore Pointer
                RET
print_buffer:   PUSH HL              ;Preserve HL,BC,AF
                PUSH BC
                PUSH AF
                LD HL,LINE_BUFFER_16 ;Load Buffer Pointer
                LD B,LENGTH          ;Load Buffer Size
                LD A,0x0D            ;Move back to the beginning of the line
                OUT (1),A            ;Output the CR character
print_loop:     LD A,(HL)            ;Load Character from Buffer
                CP "|"               ;Check if it is a Cursor
                JR NZ,PRT_Continue   ;If No,Skip
                BIT 6,C              ;If Yes,Check the bit 6 of C (C represents numbers of ticks of the loop from 0-255)
                JR NZ,PRT_CONTINUE   ;If it is 1,Print it out
                JR PRT_Finally       ;If not,Skip it! (Actually i should print space but nvm as currently there will be nothing behind the pointer)
PRT_Continue:   OUT (1),A            ;Output Character
PRT_Finally:    INC HL               ;Increase Buffer Pointer
                DEC B                ;Decrease Counter
                JR NZ,print_loop     ;Check Counter and continue loop if nonZero
                POP AF               ;Restore AF BC HL
                POP BC
                POP HL
                RET
init:           LD SP,$FFFF          ;Init Stack
                LD HL,LINE_BUFFER_16 ;Init Pointer
                LD DE,LINE_BUFFER_16 + LENGTH - 1     ;Limit the Character Per Line
                CALL reset_buffer    ;Init Buffer
                JP main
main:           CALL PRINT_BUFFER  ;Update Console
                INC C
                IN A,(0)           ;Check if Incoming Character
                AND 1              ;Check the LSB
                JR Z,main          ;Skip Loop If Nothing is comming from Console :|

                IN A,(1)           ;Input Character
                PUSH HL            ;Preserve HL
                DEC HL             ;DEC for Checking
                bit 7,H            ;Check If Less Than 0x8000 After Decrease by 1
                POP HL             ;Restore HL (Does not affect flags)
                JR Z,ContinueSpecM1;Ignore BackSpace if it will cause UnderFlow
                CP 0x08            ;Check if its BackSpace
                JR NZ,ContinueSpecM1 ;If Not,Skip
                LD (HL)," "        ;Clear Current Buffer Pointer Address Data
                DEC HL             ;Decrease the Buffer Pointer Address
                LD (HL),"|"        ;Replace with the "|" symbol
                JR main            ;Continue the Loop as BackSpace is already handled
ContinueSpecM1: CP 0x0D            ;Check if its CR (Enter)
                JR NZ,ContinueSpecM2 ;If Not,Continue!
                CALL reset_buffer  ;If Yes,Reset Buffer
                LD A,0x0A          ;Do a New Line!
                OUT (1),A          ;Output \n
                JP main            ;Skip the unnessary checks below
ContinueSpecM2: EX DE,HL           ;Exchange HL and DE for Difference Calculation
                PUSH HL            ;Preserve HL
                AND A              ;Clear Flag
                SBC HL,DE          ;to HL-DE (but it was exchanged so its actually DE-HL)
                POP HL             ;restore HL(But Actually Storing DE's content ) , not affecting Flags
                EX DE,HL           ;Exchange HL back
                JR Z,main          ;If Reached Limit,Ignore Input
                LD (HL),A          ;Load Character into Buffer
                INC HL             ;Inc Buffer Pointer
                LD (HL),0x7C       ;Load Character '|' on to the next place
                JP main            ;LOOP
.ent init             ;Boot in INIT (For Better Compatibility,put init onto 0x0000 for CP/M etc. execution)
.org 0x8000           ;RAM Part
Line_Buffer_16:        DB " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "  ;Line_Buffer
Line_Buffer_16_Default:DB "|"," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," "  ;Default Line Buffer Content for using LDIR to clear it anytime :O

;I think I done enough today :)
;All Command i want:
;W HEX4DIGITADDRESS HEX2DIGITDATA     for writing into ram
;R HEX4DIGITADDRESS                   for reading the RAM onto screen
;EXEC ADDRESS                         CALL that ADDRESS
;(The above thing should(I think...?) be able to let me write some cool programs with Machine Code (Yeah u heard it right,MACHINE CODE :skull: not assembly anymore))
