LD SP,1000H
CALL BubbleSort
HALT

BubbleSort:
    CALL CopyData
    PUSH BC
    PUSH DE
    LD BC,(DataLength)
    LD HL,DataAfterSort
    INC HL,
Outer_Loop:
Inner_Loop:
    LD DE,BC
    DEC DE
    JR NZ,Inner_Loop
    DEC BC
    JR NZ,Outer_Loop
    POP DE
    POP BC
    RET

CopyData:
    PUSH HL
    PUSH DE
    PUSH BC
    LD HL,DataForSort
    LD BC,(DataLength)
    LD DE,DataAfterSort
    LDIR
    POP BC
    POP DE
    POP HL
    RET

Compare_Swap:
    
    RET
DataLength:
    DW 16
DataForSort:
    DB 146,198,156,34,168,219,237,126,112,95,113,188,250,81,202,172
DataAfterSort:
    DB 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
